export interface Location {
  id: string;
  name: string;
  state: string;
  country: string;
  phase: string;
  latitude: number;
  longitude: number;
  description: string;
  history: string;
  spiritual: string;
  cultural: string;
  events: string;
  temple?: string;
  bestTimeToVisit: string;
  nearestCity: string;
  distance?: string;
  imageUrl?: string;
  highlights: string[];
}

export const ramLocations: Location[] = [
  {
    id: "ayodhya",
    name: "Ayodhya",
    state: "Uttar Pradesh",
    country: "India",
    phase: "Birth & Early Life",
    latitude: 26.8124,
    longitude: 82.0011,
    description: "The sacred birthplace of Shri Ram and capital of the ancient Kosala kingdom",
    history: "Ayodhya was the capital of the Kosala kingdom and is one of the seven sacred cities in Hinduism. It lies on the banks of the Sarayu River, where Ram was born to King Dashrath and Queen Kausalya.",
    spiritual: "Ayodhya is the holiest city for Ram devotees worldwide. The newly constructed Ram Mandir is an architectural marvel blending ancient Vedic principles with modern construction. It's believed that visiting Ayodhya purifies the soul and brings divine blessings.",
    cultural: "Ayodhya has rich cultural heritage with numerous temples, ghats, and historical sites. The city celebrates Ram Navami with grand processions and spiritual activities. Local traditions include Ramleela performances and devotional songs.",
    events: "Ram Mandir darshan, Ram Navami celebrations, Ayodhya Deepotsav (lighting of millions of lamps)",
    temple: "Ram Mandir",
    bestTimeToVisit: "October to March",
    nearestCity: "Faizabad",
    distance: "6 km from Faizabad",
    highlights: ["Ram Mandir", "Sarayu River", "Hanuman Garhi", "Kanak Bhawan", "Ram Ki Paidi"]
  },
  {
    id: "janakpur",
    name: "Janakpur (Mithila)",
    state: "Janakpur",
    country: "Nepal",
    phase: "Birth & Early Life",
    latitude: 26.9124,
    longitude: 85.9253,
    description: "Birthplace of Sita and site of her Swayamvar where Ram won her hand",
    history: "Janakpur was the capital of the kingdom of Videha and the home of King Janaka. It's the birthplace of Sita, who was found in a furrow of the field. The famous Swayamvar took place here where Ram broke the divine bow of Shiva to win Sita's hand.",
    spiritual: "This is one of the most sacred pilgrimage sites for devotees of Sita and Ram. The Vivaha Mandap (marriage pavilion) marks the spot where the divine wedding occurred. Visiting here grants blessings of eternal love and marital harmony.",
    cultural: "Janakpur is famous for Mithila art, traditional paintings depicting stories of Ram and Sita. The city celebrates Vivaha Mandap Utsav with colorful processions, cultural programs, and Mithila art exhibitions.",
    events: "Sita Swayamvar reenactments, Mithila art festivals, Vivaha Mandap darshan",
    temple: "Janaki Mandir",
    bestTimeToVisit: "October to March",
    nearestCity: "Janakpur",
    highlights: ["Janaki Mandir", "Vivaha Mandap", "Ram Navami Mela", "Sita Kund", "Mithila Art Center"]
  },
  {
    id: "chitrakoot",
    name: "Chitrakoot",
    state: "Madhya Pradesh",
    country: "India",
    phase: "Vanvās Begins",
    latitude: 25.2083,
    longitude: 80.8017,
    description: "Sacred place where Ram established his hermitage during 14-year exile and Bharat met him",
    history: "Located at the confluence of the Yamuna and Mandakini rivers, Chitrakoot was where Ram, Sita, and Lakshman built their hermitage (hut). Bharat came here seeking Ram to convince him to return, but Ram remained steadfast in his vow to his father.",
    spiritual: "Chitrakoot is believed to be the place where devout meditation leads to direct communion with the divine. Walking the Parikrama (circumambulation) around the sacred area grants spiritual purification. The caves where Ram meditated are still preserved.",
    cultural: "The local Bhar tribe has a unique connection to Ram, with traditions passed down through generations. The city hosts grand Ramleela performances and maintains ancient rituals connected to Ram's exile period.",
    events: "Ram Navami fair, Chitrakoot Parikrama, Ramleela performances",
    temple: "Ramanuja Temple",
    bestTimeToVisit: "September to February",
    nearestCity: "Satna",
    distance: "50 km from Satna",
    highlights: ["Mandakini River", "Ramghat", "Bharat Milap Temple", "Hanuman Dhara", "Devangana Cave"]
  },
  {
    id: "panchavati",
    name: "Panchavati",
    state: "Maharashtra",
    country: "India",
    phase: "Deep Forest Journey",
    latitude: 19.8975,
    longitude: 75.3281,
    description: "Hermitage in the forest where Sita was abducted by Ravana, located in Nashik region",
    history: "Panchavati was where Ram, Sita, and Lakshman spent most of their 14-year exile in the Dandakaranya forest. Here, the tragic incident of Sita's abduction by Ravana occurred. The forests around Panchavati are mentioned extensively in the Ramayana.",
    spiritual: "Despite the tragedy that occurred here, Panchavati is considered a place of immense spiritual power. Meditating at this location is believed to strengthen devotion and provide protection. Many sages have performed rigorous tapasya (austerities) here.",
    cultural: "The region is rich with tribal culture and ancient traditions. Nashik is home to the Kumbh Mela every 12 years, one of the world's largest religious gatherings. Local customs include pilgrimages to multiple temples connected to the Ramayana.",
    events: "Kumbh Mela (every 12 years), Ram Navami celebrations, Ramghat aarti",
    temple: "Kalaram Temple, Panchavati Temple",
    bestTimeToVisit: "September to February",
    nearestCity: "Nashik",
    distance: "30 km from Nashik",
    highlights: ["Godavari River", "Panchavati Temple", "Sita Haran Spot", "Tapovan", "Anjaneri Hill"]
  },
  {
    id: "hampi",
    name: "Hampi",
    state: "Karnataka",
    country: "India",
    phase: "Search for Sita",
    latitude: 15.3350,
    longitude: 76.4789,
    description: "Location of Kishkindha kingdom where Ram met Hanuman and Sugriva, considered a UNESCO World Heritage Site",
    history: "Hampi is the site of the ancient Kishkindha kingdom ruled by Sugriva. Here Ram met the monkey king Sugriva and his devoted follower Hanuman. This meeting was crucial in Ram's mission to rescue Sita. Hanuman's leap across the ocean to Lanka is commemorated here.",
    spiritual: "Hampi is a place of divine meetings where earthly and heavenly realms unite. Visiting Hampi grants blessings of loyalty, friendship, and unwavering faith. The energy of the place is believed to enhance spiritual growth and resolve.",
    cultural: "Hampi is a repository of Dravidian architecture and ancient Indian art. The temples showcase intricate stone carvings depicting scenes from the Ramayana and Mahabharata. Local festivals celebrate the meeting of Ram and Hanuman.",
    events: "Ram-Hanuman Milap celebrations, Temple festivals, Cultural performances",
    temple: "Virupaksha Temple",
    bestTimeToVisit: "October to March",
    nearestCity: "Hospet",
    distance: "15 km from Hospet",
    highlights: ["Virupaksha Temple", "Anjanadri Hill", "Matanga Hill", "Hampi Bazaar", "Tungabhadra River"]
  },
  {
    id: "rameswaram",
    name: "Rameswaram",
    state: "Tamil Nadu",
    country: "India",
    phase: "Return & Coronation",
    latitude: 9.2876,
    longitude: 79.1808,
    description: "Sacred temple town where Ram installed a Shiva Linga after defeating Ravana and beginning his return journey",
    history: "After the victory in Lanka, Ram returned to the mainland and installed a Shiva Linga (Ramanathaswamy Temple) at Rameswaram. This was done to absolve himself of the sin of killing Ravana. The town is also believed to be the point from which Ram Setu (bridge) was built.",
    spiritual: "Rameswaram is one of the four most important pilgrimage sites (Char Dham) in Hinduism. It's believed that bathing in the holy waters and visiting the temple grants moksha (liberation). The temple tanks here have water from all sacred rivers of India.",
    cultural: "The Ramanathaswamy Temple is an architectural marvel with grand corridors and intricate stone columns. The town celebrates Ram's return with grand processions and cultural events. Local traditions include circumambulation of the town.",
    events: "Rameswaram Temple celebrations, Maha Shivaratri, Panguni Uthiram",
    temple: "Ramanathaswamy Temple",
    bestTimeToVisit: "October to February",
    nearestCity: "Rameswaram",
    highlights: ["Ramanathaswamy Temple", "Ram Setu (Adam's Bridge)", "Agni Theertham Beach", "Dhanushkodi"]
  },
  {
    id: "srirangam",
    name: "Srirangam",
    state: "Tamil Nadu",
    country: "India",
    phase: "Return & Coronation",
    latitude: 10.8930,
    longitude: 78.6569,
    description: "One of the largest temple complexes in the world, located where Ram visited on return from Lanka",
    history: "Srirangam is one of the most significant Vaishnava temples dedicated to Lord Vishnu. According to tradition, Ram visited this temple on his journey back from Lanka. The temple complex contains concentric rectangular walls with multiple sanctuaries.",
    spiritual: "The Sri Ranganathaswamy Temple is a place of immense spiritual energy dedicated to Vishnu. Visiting here and participating in the daily rituals is believed to grant divine grace and protection. The temple represents the cosmic order (Ranga).",
    cultural: "Srirangam is a cultural center with an active community maintaining Vedic traditions and classical arts. The town hosts numerous festivals throughout the year with elaborate temple rituals and processions. South Indian classical music and dance are regularly performed here.",
    events: "Vaikunta Ekadashi, Temple festivals, Chariot processions",
    temple: "Sri Ranganathaswamy Temple",
    bestTimeToVisit: "October to February",
    nearestCity: "Tiruchirappalli",
    highlights: ["Sri Ranganathaswamy Temple", "Kaveri River", "Temple Museum", "Festive processions"]
  },
  {
    id: "ayodhya-return",
    name: "Ayodhya (Return & Coronation)",
    state: "Uttar Pradesh",
    country: "India",
    phase: "Return & Coronation",
    latitude: 26.8124,
    longitude: 82.0011,
    description: "Ram's triumphant return to Ayodhya after 14 years and his grand coronation ceremony",
    history: "After 14 years of exile and the victory over Ravana, Ram returned to Ayodhya with Sita and Lakshman. His return was celebrated with unparalleled jubilation. The coronation (Pattabhisheka) ceremony made Ram the king of Ayodhya and ushered in a golden age (Ram Rajya).",
    spiritual: "Ram's return symbolizes the triumph of good over evil and the establishment of righteousness. The coronation represents the establishment of divine rule on earth. This period is celebrated as the ideal kingdom where all subjects are happy and just.",
    cultural: "The coronation of Ram is celebrated annually during Ram Navami. The city lights up with millions of lamps during the Ayodhya Deepotsav festival. Traditional ceremonies and rituals associated with the coronation are reenacted during celebrations.",
    events: "Ayodhya Deepotsav, Ram Navami, Coronation anniversary celebrations",
    temple: "Ram Mandir",
    bestTimeToVisit: "October to March",
    nearestCity: "Faizabad",
    highlights: ["Ram Mandir", "Sarayu River", "Coronation site", "Dashrath Mahal"]
  },
  {
    id: "valmiki-ashram",
    name: "Valmiki Ashram",
    state: "Uttar Pradesh",
    country: "India",
    phase: "Post-Coronation",
    latitude: 26.2167,
    longitude: 81.5667,
    description: "Sacred ashram near Bithoor where Sita was exiled and bore Ram's sons Luv and Kush",
    history: "After Ram's coronation, due to public rumors about Sita's captivity in Lanka, Ram was forced to exile her to Valmiki Ashram. Here, Sita gave birth to Ram's twin sons, Luv and Kush. Valmiki, the great sage and poet, composed the Ramayana here.",
    spiritual: "This ashram is a place of profound spiritual significance representing sacrifice and maternal love. Despite her suffering, Sita's unwavering devotion to Ram is celebrated here. Visiting this site grants blessings of strength, compassion, and spiritual wisdom.",
    cultural: "The ashram is associated with the composition of the Ramayana, one of the world's greatest epics. The local culture celebrates this connection through Ramleela performances and literary festivals. The tradition of epic recitation (Katha) continues in the area.",
    events: "Sita Jayanti, Valmiki Jayanti, Annual Ramayana recitation",
    temple: "Valmiki Ashram Temple",
    bestTimeToVisit: "October to April",
    nearestCity: "Kanpur",
    distance: "20 km from Kanpur (Bithoor)",
    highlights: ["Valmiki Ashram", "Sangam with Yamuna", "Ram Ghat", "Sita Temple"]
  },
  {
    id: "sarayu-river",
    name: "Sarayu River",
    state: "Uttar Pradesh",
    country: "India",
    phase: "Birth & Early Life / Post-Coronation",
    latitude: 26.8138,
    longitude: 82.0050,
    description: "Sacred river where Ram was born and where he took his final departure in Jal Samadhi",
    history: "The Sarayu River is central to Ram's life story. It was on the banks of Sarayu that Ram was born and spent his childhood. At the end of his earthly life, Ram entered the Sarayu River in what's known as Jal Samadhi (water burial), transcending the mortal realm.",
    spiritual: "The Sarayu is considered one of the most sacred rivers in Hinduism. Bathing in its waters is believed to purify the soul and grant divine grace. Many saints and sages have meditated on its banks seeking spiritual enlightenment.",
    cultural: "The river is the lifeblood of Ayodhya. Daily rituals and aarti (prayer ceremonies) take place along its ghats. The tradition of bathing at dawn and evening prayers continues as it has for thousands of years. Local communities celebrate the river with festivals and ceremonies.",
    events: "Daily aarti, Sarayu Jayanti, Spiritual gatherings",
    bestTimeToVisit: "October to March",
    nearestCity: "Ayodhya",
    highlights: ["Ram Ghat", "Sarayu Ghats", "Morning prayers", "Aarti ceremonies", "Pilgrimage routes"]
  },
  {
    id: "mandakini-river",
    name: "Mandakini River",
    state: "Madhya Pradesh",
    country: "India",
    phase: "Vanvās Begins",
    latitude: 25.1889,
    longitude: 80.8286,
    description: "Sacred river at Chitrakoot where Ram bathed daily during exile and performed rituals",
    history: "The Mandakini River, a tributary of the Yamuna, flows through Chitrakoot. During his exile, Ram and his family bathed in this river daily and performed sacred rituals on its banks. Many episodes of the Ramayana are associated with the Mandakini.",
    spiritual: "Bathing in the Mandakini is believed to grant spiritual purification and divine blessings. The river is sacred to devotees of Ram who believe that the waters carry his divine energy. Meditation on the river banks is said to enhance spiritual practice.",
    cultural: "The Mandakini is celebrated in local arts, music, and literature. The river is the center of cultural activities in Chitrakoot with festivals and ceremonies taking place along its banks. Local traditions maintain the sanctity and cleanliness of the river.",
    events: "Religious ceremonies, Parikrama (circumambulation), Festival celebrations",
    bestTimeToVisit: "September to February",
    nearestCity: "Satna",
    highlights: ["Ramghat", "Mandakini temples", "Meditation spots", "Pilgrimage routes", "Sacred confluence"]
  },
  {
    id: "godavari-river",
    name: "Godavari River",
    state: "Maharashtra",
    country: "India",
    phase: "Deep Forest Journey",
    latitude: 19.8975,
    longitude: 75.3281,
    description: "Major river where Ram spent time during exile and where Sita was abducted from the banks",
    history: "The Godavari River is one of the longest rivers in India. During exile, Ram, Sita, and Lakshman spent time on the banks of the Godavari. The incident of Sita's abduction occurred near Panchavati on the Godavari banks.",
    spiritual: "The Godavari is one of the seven sacred rivers of India. Bathing in its waters during pilgrimages grants divine blessings. Devotees believe the river carries the grace of Ram and provides protection and spiritual advancement.",
    cultural: "The Godavari is sacred to South Indian culture and is celebrated in regional festivals. The Nashik Kumbh Mela held on its banks is one of the world's largest religious gatherings. Local traditions and rituals have been maintained for millennia.",
    events: "Kumbh Mela (every 12 years), Temple festivals, Ritual bathing",
    bestTimeToVisit: "September to February",
    nearestCity: "Nashik",
    highlights: ["Panchavati", "Godavari Ghats", "Temples", "Ramkund", "Sacred confluence"]
  },
  {
    id: "pampa-sarovar",
    name: "Pampa Sarovar",
    state: "Karnataka",
    country: "India",
    phase: "Search for Sita",
    latitude: 15.3069,
    longitude: 76.4878,
    description: "Holy lake where Ram met the devotee Shabari who offered him berries with devotion",
    history: "Pampa Sarovar (lake) is located near Hampi. Here, Ram met Shabari, an elderly woman and devoted ascetic. Despite her low caste and simple means, Shabari's pure devotion earned her Ram's blessings. She is remembered for testing berries with her teeth before offering them to Ram.",
    spiritual: "Pampa Sarovar represents the meeting of Ram's grace with human devotion. Visiting this lake grants blessings of unwavering faith and divine acceptance. The story of Shabari teaches that devotion transcends all social boundaries.",
    cultural: "The lake is surrounded by temples and ashrams. Local traditions celebrate Shabari as a symbol of true devotion. The story of Shabari and Ram is performed in Ramleela and retold in spiritual discourse throughout South India.",
    events: "Shabari Jayanti, Temple festivals, Spiritual gatherings",
    temple: "Shabari Temple",
    bestTimeToVisit: "October to March",
    nearestCity: "Hospet",
    highlights: ["Pampa Sarovar", "Shabari Temple", "Sacred ghats", "Meditation areas"]
  },
  {
    id: "anjanadri-hill",
    name: "Anjanadri Hill",
    state: "Karnataka",
    country: "India",
    phase: "Search for Sita",
    latitude: 15.3419,
    longitude: 76.5114,
    description: "Sacred mountain, birthplace of Hanuman, where Ram granted him divine status",
    history: "Anjanadri Hill in Hampi region is revered as the birthplace of Hanuman, the monkey deity and Ram's greatest devotee. It was on this hill that Hanuman first met Ram and pledged his eternal devotion. The hill is considered sacred ground.",
    spiritual: "Anjanadri represents unwavering devotion and loyalty to the divine. Visiting the birthplace of Hanuman grants blessings of strength, courage, and devotion. Meditating here is believed to enhance one's ability to serve the divine purpose.",
    cultural: "The hill is a pilgrimage site for devotees of Hanuman. Local traditions include circumambulation of the hill and prayers to Hanuman. The culture celebrates Hanuman as the ideal devotee - selfless, loyal, and eternally dedicated to Ram.",
    events: "Hanuman Jayanti, Temple festivals, Pilgrimage rituals",
    temple: "Hanuman Temple",
    bestTimeToVisit: "October to March",
    nearestCity: "Hospet",
    highlights: ["Hanuman Cave", "Temple at summit", "Panoramic views", "Pilgrimage trails"]
  },
  {
    id: "dhanushkodi",
    name: "Dhanushkodi",
    state: "Tamil Nadu",
    country: "India",
    phase: "Return & Coronation",
    latitude: 9.1667,
    longitude: 79.1667,
    description: "Southern tip of India where Ram built the bridge to Lanka; scene of the final battle",
    history: "Dhanushkodi, meaning 'the bow's end,' is the southern extremity of India. From here, Ram's army of Vanara (monkeys) and bears constructed Ram Setu, the legendary bridge to Lanka. This is where the final preparations for the war against Ravana took place.",
    spiritual: "Dhanushkodi is the meeting point of the Indian Ocean and the Bay of Bengal. It represents the end of the search for Sita and the beginning of the final victory. Visiting here grants blessings of determination and successful completion of divine missions.",
    cultural: "Dhanushkodi is steeped in legend and mythology. Local communities maintain traditions connected to Ram Setu and the bridge construction. The place is celebrated as a symbol of Hindu engineering prowess and divine planning.",
    events: "Ram Setu Puja, Coastal pilgrimage rituals, Temple celebrations",
    bestTimeToVisit: "October to February",
    nearestCity: "Rameswaram",
    distance: "10 km from Rameswaram",
    highlights: ["Ram Setu viewpoint", "Ocean confluence", "Pilgrimage site", "Historical ruins"]
  },
  {
    id: "ram-setu",
    name: "Ram Setu (Adam's Bridge)",
    state: "Tamil Nadu / Sri Lanka",
    country: "India/Sri Lanka",
    phase: "Return & Coronation",
    latitude: 8.9667,
    longitude: 79.1833,
    description: "Legendary bridge built by Ram's army connecting India to Lanka, now partially submerged",
    history: "Ram Setu is the legendary bridge built by Hanuman and the Vanara army to enable Ram's forces to cross to Lanka. The bridge was constructed with floating stones that had Ram's name written on them. It's one of the world's most famous legendary engineering feats.",
    spiritual: "Ram Setu is a symbol of the divine plan and the power of faith and collaboration. It represents how all of creation can be mobilized for righteous purposes. Visiting this site or viewing it from the Indian shores grants blessings of faith and divine protection.",
    cultural: "Ram Setu is celebrated in Hindu culture as a monument to engineering genius and devotion. It appears in ancient texts, sculptures, and art throughout India. Recent archaeological studies have shown natural formations that align with the legendary descriptions.",
    events: "Ram Setu Darshan, Coastal pilgrimage, Educational tours",
    bestTimeToVisit: "October to February",
    nearestCity: "Rameswaram",
    highlights: ["Submerged bridge structure", "Ocean views", "Pilgrimage sites", "Astronomical alignment"]
  },
  {
    id: "lanka",
    name: "Lanka",
    state: "Western Province",
    country: "Sri Lanka",
    phase: "Return & Coronation",
    latitude: 6.9271,
    longitude: 80.7789,
    description: "Ancient kingdom ruled by Ravana where Sita was held captive and the great war took place",
    history: "Lanka was the prosperous kingdom of Ravana, the demon king with ten heads. Sita was kept captive in Ashok Vatika for nearly a year. The great battle between Ram's forces and Ravana's armies took place here, culminating in Ravana's defeat and Sita's rescue.",
    spiritual: "Lanka represents the realm of material illusions and ego. The battle here symbolizes the eternal struggle between good and evil, divine law and chaos. Visiting Lanka grants insights into karma, dharma, and the triumph of righteousness.",
    cultural: "Sri Lanka has preserved many temples and sites connected to the Ramayana. The culture celebrates the Ramayana as a defining epic. Local traditions include Ramayana recitations and cultural performances that blend Hindu and Buddhist elements.",
    events: "Ramayana festivals, Temple ceremonies, Cultural programs",
    temple: "Various Ramayana temples",
    bestTimeToVisit: "October to February",
    nearestCity: "Colombo",
    highlights: ["Ashok Vatika", "Ravana's Palace site", "Ramayana temples", "War sites"]
  },
  {
    id: "ravana-palace",
    name: "Ravana's Palace",
    state: "Western Province",
    country: "Sri Lanka",
    phase: "Return & Coronation",
    latitude: 6.8950,
    longitude: 80.7758,
    description: "Site of Ravana's legendary golden palace where Sita was held and final battle occurred",
    history: "Ravana's palace was the center of his power in Lanka. It was a marvel of ancient architecture with golden spires and valuable gems. Within its walls, Sita was held captive, and here the final confrontation between Ram and Ravana took place.",
    spiritual: "The palace represents both worldly achievements and spiritual emptiness. Ravana's downfall demonstrates that material wealth and power without virtue lead to destruction. Visiting this site teaches humility and the importance of dharma.",
    cultural: "The palace is remembered in Sri Lankan culture as a symbol of a once-glorious kingdom. Local traditions celebrate the complex character of Ravana, who was a scholar and devotee despite his evil actions. The site is important for understanding the Ramayana's spiritual message.",
    events: "Guided tours, Educational programs, Archaeological research",
    bestTimeToVisit: "October to February",
    nearestCity: "Colombo",
    highlights: ["Palace ruins", "Archaeological sites", "Historical inscriptions"]
  },
  {
    id: "ashok-vatika",
    name: "Ashok Vatika",
    state: "Central Province",
    country: "Sri Lanka",
    phase: "Return & Coronation",
    latitude: 6.9263,
    longitude: 80.8325,
    description: "Sacred garden where Sita was imprisoned by Ravana, now venerated as a spiritual site",
    history: "Ashok Vatika was a beautiful garden where Sita was confined during her captivity in Lanka. Despite being in a garden, Sita remained faithful to Ram, refusing Ravana's advances. Here, Hanuman found Sita and gave her news of Ram's coming rescue.",
    spiritual: "Ashok Vatika is a powerful symbol of devotion and faith. Despite all hardships and temptations, Sita's unwavering loyalty to Ram represents the soul's devotion to the divine. Visiting this place grants strength, faith, and spiritual clarity.",
    cultural: "The garden is celebrated in Tamil, Telugu, and other Southern Indian literature and arts. Sita's fortitude in Ashok Vatika is considered the ultimate example of feminine virtue and courage. Local traditions celebrate women of faith and devotion.",
    events: "Sita Jayanti, Temple ceremonies, Pilgrimage gatherings",
    temple: "Sita Temple",
    bestTimeToVisit: "October to February",
    nearestCity: "Nuwara Eliya",
    highlights: ["Temple site", "Sita's prison area", "Garden remains", "Spiritual energy point"]
  },
  {
    id: "lepakshi",
    name: "Lepakshi",
    state: "Andhra Pradesh",
    country: "India",
    phase: "Return & Coronation",
    latitude: 13.8750,
    longitude: 79.3858,
    description: "Temple where Jatayu, the eagle warrior, fell after his battle with Ravana",
    history: "Lepakshi means 'the rise of the eagle' in Telugu. When Ravana was abducting Sita, Jatayu, the noble vulture king and friend of Ram's father Dashrath, fought Ravana to save Sita. Fatally wounded, Jatayu fell at this location, where Ram met him and granted him moksha.",
    spiritual: "Lepakshi is a place of heroic sacrifice and noble ideals. Visiting here grants blessings of courage and righteousness. The story of Jatayu teaches that age is no barrier to standing up for justice and that sacrifice in the service of dharma leads to liberation.",
    cultural: "The Lepakshi temple is architecturally significant with intricate stone work and sculptures depicting Ramayana scenes. Local culture celebrates Jatayu as a hero and symbol of duty. The site is important for understanding the Ramayana's moral teachings.",
    events: "Jatayu Jayanti, Temple festivals, Educational programs",
    temple: "Lepakshi Temple",
    bestTimeToVisit: "October to March",
    nearestCity: "Hindupur",
    distance: "60 km from Bangalore",
    highlights: ["Main temple", "Jatayu sculptures", "Stone carvings", "Ancient art"]
  },
  {
    id: "sitamarhi",
    name: "Sitamarhi",
    state: "Bihar",
    country: "India",
    phase: "Birth & Early Life",
    latitude: 26.5960,
    longitude: 85.4899,
    description: "Sacred site where Sita is believed to have been born in the fields of King Janaka",
    history: "Sitamarhi is located about 40 km from Janakpur. It's believed to be the site where baby Sita was discovered in a furrow of the field by King Janaka. The area is steeped in traditions connected to Sita's birth and infancy.",
    spiritual: "Sitamarhi is sacred to devotees of Sita and represents divine femininity and shakti (energy). Visiting here is believed to grant blessings of fertility, prosperity, and protection. The site is especially significant for women seekers of spiritual wisdom.",
    cultural: "The region maintains strong traditions connected to Sita. The Sitamarhi temple is an important pilgrimage center where women gather for rituals and prayers. Local culture celebrates Sita as the ultimate ideal of virtue, loyalty, and feminine power.",
    events: "Sita Jayanti, Women's pilgrimages, Temple festivals",
    temple: "Sita Mandir",
    bestTimeToVisit: "October to March",
    nearestCity: "Sitamarhi",
    highlights: ["Sita Mandir", "Birth site", "Sacred fields", "Pilgrimage rituals"]
  },
  {
    id: "prayagraj",
    name: "Prayagraj (Allahabad)",
    state: "Uttar Pradesh",
    country: "India",
    phase: "Vanvās Begins / Return & Coronation",
    latitude: 25.4358,
    longitude: 81.8463,
    description: "Sacred city at the confluence of Ganges, Yamuna, and mythical Saraswati rivers",
    history: "Prayagraj is one of the oldest cities in India. Ram visited here during his exile and again on his return to Ayodhya. The Bharadwaj Ashram where Ram received guidance is located here. The city is where the mythical Saraswati river meets the Ganges and Yamuna.",
    spiritual: "Prayagraj is one of the seven sacred cities and one of the four pilgrimage sites of India (Char Dham). The Kumbh Mela, held here every 12 years, is the world's largest religious gathering. Bathing at the Sangam (confluence) grants liberation from the cycle of birth and death.",
    cultural: "Prayagraj is a center of Vedic learning and culture. The city has hosted saints, scholars, and spiritual seekers for millennia. Ramayana recitations and spiritual discourses are regular features of the city's cultural life.",
    events: "Kumbh Mela (every 12 years), Magh Mela (every year), Triveni Sangam Puja",
    temple: "Bharadwaj Ashram Temple",
    bestTimeToVisit: "October to March",
    nearestCity: "Prayagraj",
    highlights: ["Triveni Sangam", "Kumbh Mela ground", "Bharadwaj Ashram", "Sacred Ghats", "Allahabad Fort"]
  },
  {
    id: "tamasa-river",
    name: "Tamasa River",
    state: "Uttar Pradesh",
    country: "India",
    phase: "Vanvās Begins",
    latitude: 25.8292,
    longitude: 81.7622,
    description: "River where Ram spent his first night of exile after leaving Ayodhya",
    history: "The Tamasa River marks the boundary of Ayodhya. On the first night of his exile, Ram, Sita, and Lakshman halted at the Tamasa River. This night was emotionally difficult as it marked the beginning of their long separation from home and loved ones.",
    spiritual: "The Tamasa represents the transition from worldly life to spiritual duty. Bathing in the river is believed to grant purification and strengthen resolve. The site reminds devotees that the spiritual path often requires sacrifice and separation from comfort.",
    cultural: "The Tamasa is remembered in local folklore and traditions. The region celebrates the start of Ram's exile with spiritual significance. Local communities maintain traditions of pilgrimage to this sacred river.",
    events: "Pilgrimage activities, Ritual bathing, Spiritual gatherings",
    bestTimeToVisit: "October to March",
    nearestCity: "Raibareli",
    highlights: ["Tamasa Ghat", "Sacred crossing point", "Pilgrimage sites"]
  },
  {
    id: "shringaverpur",
    name: "Shringaverpur",
    state: "Uttar Pradesh",
    country: "India",
    phase: "Vanvās Begins",
    latitude: 25.9111,
    longitude: 81.8222,
    description: "Site where Nishad king Guha met Ram and ferried him across the Ganges",
    history: "Shringaverpur was ruled by Guha, a Nishad (boatman) king. When Ram arrived here seeking passage across the Ganges, Guha recognized him and became his devoted follower. Guha's love and service represent the equality of devotion regardless of caste or status.",
    spiritual: "Shringaverpur is a place where divine grace meets human devotion transcending social boundaries. Guha's instant recognition and service to Ram demonstrate the power of pure devotion. The site teaches that all are equal before the divine.",
    cultural: "The region celebrates Guha's story as an example of dharma and loyalty. Local communities maintain traditions of boatmanship and pilgrimage. The story of Guha appears in regional variations of the Ramayana.",
    events: "Guha Jayanti, Temple celebrations, Pilgrimage activities",
    temple: "Guha Temple",
    bestTimeToVisit: "October to March",
    nearestCity: "Prayagraj",
    distance: "40 km from Prayagraj",
    highlights: ["Guha Mandir", "Ganges crossing point", "Boating traditions", "Spiritual site"]
  },
  {
    id: "nashik",
    name: "Nashik",
    state: "Maharashtra",
    country: "India",
    phase: "Deep Forest Journey",
    latitude: 19.9975,
    longitude: 73.7898,
    description: "Pilgrimage center at the confluence of Godavari River, sacred to Ram's exile period",
    history: "Nashik holds deep significance in the Ramayana. Ram, Sita, and Lakshman spent considerable time in the Nashik region during their 14-year exile. The city is mentioned as a place where Ram performed rituals and meditation on the banks of the Godavari.",
    spiritual: "Nashik is a major spiritual center hosting the Kumbh Mela every 12 years, one of Hinduism's holiest gatherings. The city is believed to be where divine nectar fell during the fight between gods and demons. Visiting here grants spiritual elevation and divine grace.",
    cultural: "Nashik is a cultural hub celebrating Maharashtrian traditions and Sanskrit learning. The city hosts numerous temples, ashrams, and cultural institutions. Traditional arts, music, and classical performances are integral to the city's identity.",
    events: "Kumbh Mela (every 12 years), Ramnavami, Daily temple rituals",
    temple: "Kalaram Temple, Panchavati Temples",
    bestTimeToVisit: "September to February",
    nearestCity: "Nashik",
    highlights: ["Godavari Ghats", "Kalaram Temple", "Panchavati", "Ramkund", "Sacred confluence"]
  },
  {
    id: "dandakaranya",
    name: "Dandakaranya Forest",
    state: "Multiple (MP, Maharashtra, Chhattisgarh)",
    country: "India",
    phase: "Deep Forest Journey",
    latitude: 21.5,
    longitude: 80.5,
    description: "Vast ancient forest where Ram spent 12 of his 14 exile years and encountered many perils",
    history: "Dandakaranya, the 'forest of punishment,' was a vast forest region spanning central India. Ram, Sita, and Lakshman traversed this forest, encountering various challenges, sages, and demons. This period lasted about 12 years of their 14-year exile.",
    spiritual: "Dandakaranya represents the spiritual journey through trials and tribulations. The forest is a metaphor for the ego and ignorance that must be traversed to achieve enlightenment. Visiting forest ashrams and sacred sites grants purification and spiritual growth.",
    cultural: "The Dandakaranya region is home to tribal communities that have maintained ancient traditions for centuries. The region celebrates its connection to the Ramayana through oral traditions, festivals, and sacred sites. Local art and crafts reflect the spiritual heritage.",
    events: "Tribal festivals, Temple pilgrimages, Spiritual retreats",
    bestTimeToVisit: "October to March",
    nearestCity: "Multiple locations in central India",
    highlights: ["Sacred ashrams", "Wildlife areas", "Ancient temples", "Pilgrimage routes", "Tribal villages"]
  },
  {
    id: "atri-ashram",
    name: "Atri Ashram",
    state: "Madhya Pradesh",
    country: "India",
    phase: "Deep Forest Journey",
    latitude: 25.1667,
    longitude: 80.8333,
    description: "Sacred ashram where Ram received blessings from Sage Atri and his wife Anasuya",
    history: "Atri Ashram was located in the Dandakaranya forest region. Sage Atri was a respected Vedic scholar and devotee. His wife Anasuya blessed Sita with virtues and spiritual strength. The visit to this ashram is depicted as a significant event in Ram's exile.",
    spiritual: "Atri Ashram is a place of spiritual wisdom and divine grace. Visiting here grants blessings of knowledge, virtue, and spiritual progress. The ashram represents the ideal of combining Vedic knowledge with practical devotion.",
    cultural: "The ashram traditions emphasize the importance of guru-shishya (teacher-student) relationships in spiritual development. Anasuya is celebrated as an ideal of womanly virtue and wisdom. Local communities maintain ashram traditions and spiritual practices.",
    events: "Spiritual retreats, Temple ceremonies, Teaching programs",
    temple: "Atri-Anasuya Mandir",
    bestTimeToVisit: "September to February",
    nearestCity: "Satna",
    distance: "45 km from Satna",
    highlights: ["Atri Ashram ruins", "Sacred cave", "Spiritual teachings site", "Forest sanctuary"]
  },
  {
    id: "sugriva-capital",
    name: "Sugriva's Capital",
    state: "Karnataka",
    country: "India",
    phase: "Search for Sita",
    latitude: 15.3,
    longitude: 76.4789,
    description: "Kishkindha kingdom where Ram met the Vanara king Sugriva and his general Hanuman",
    history: "Sugriva was the king of the Vanara kingdom. Due to a conflict with his brother Bali, Sugriva was forced into hiding. When Ram met Sugriva, he not only helped rescue Sita but also restored Sugriva to his throne by defeating Bali in combat.",
    spiritual: "The meeting of Ram and Sugriva represents divine intervention in worldly affairs and the establishment of justice. Sugriva's kingdom symbolizes a society where dharma prevails. Visiting these sites grants blessings of courage and righteous victory.",
    cultural: "The Vanara kingdom represents an idealized society in Hindu mythology. Local culture celebrates the courage and loyalty of the Vanara warriors. The region is rich with temples and traditions celebrating these noble qualities.",
    events: "Temple festivals, Pilgrimages, Cultural celebrations",
    temple: "Multiple Sugriva temples",
    bestTimeToVisit: "October to March",
    nearestCity: "Hospet",
    highlights: ["Sugriva's throne area", "Kingdom sites", "Temple complexes", "Sacred grounds"]
  },
  {
    id: "rishyamukha-parvat",
    name: "Rishyamukha Parvat",
    state: "Karnataka",
    country: "India",
    phase: "Search for Sita",
    latitude: 15.3667,
    longitude: 76.5,
    description: "Mountain where Sugriva took refuge and met Ram for divine alliance",
    history: "Rishyamukha Parvat was a sacred mountain where Sugriva took refuge, protected by a curse that kept demons away. It was here that Ram and Sugriva first met and formed an alliance. This meeting was crucial in the quest to rescue Sita.",
    spiritual: "Rishyamukha represents a place of refuge and divine protection. The mountain's mystical properties symbolize how the divine ensures the meeting of souls destined to help each other. Visiting grants spiritual protection and divine guidance.",
    cultural: "The mountain is celebrated in local culture as a sacred site. Pilgrims trek to the summit for meditation and prayer. The site is important for understanding the geography and spiritual topography of the Ramayana.",
    events: "Mountain pilgrimages, Meditation retreats, Temple festivals",
    temple: "Mountain temples",
    bestTimeToVisit: "October to March",
    nearestCity: "Hospet",
    highlights: ["Mountain summit", "Sacred cave", "Pilgrimage trails", "Panoramic views"]
  },
  {
    id: "matanga-hill",
    name: "Matanga Hill",
    state: "Karnataka",
    country: "India",
    phase: "Search for Sita",
    latitude: 15.3642,
    longitude: 76.4736,
    description: "Hill where Hanuman and the Vanara army prepared for war and scouted Lanka",
    history: "Matanga Hill was used as a strategic location for the Vanara army to train and prepare for the war against Ravana. Hanuman leaped from this hill toward Lanka to scout the enemy territory. The hill overlooks the plains where the army assembled.",
    spiritual: "Matanga Hill represents preparation for spiritual warfare against ignorance and ego. The view from the summit symbolizes the clarity of vision needed for spiritual progress. Visiting grants blessings of courage and strategic wisdom.",
    cultural: "The hill is an important archaeological and cultural site with evidence of ancient habitation. Local communities maintain traditions of this historic battle site. The view of the surrounding landscape connects visitors to the epic narrative.",
    events: "Pilgrimage trails, Meditation sites, Historical tours",
    bestTimeToVisit: "October to March",
    nearestCity: "Hospet",
    highlights: ["Hill summit", "Vanara army site", "Lanka viewing point", "Temple structures"]
  },
  {
    id: "sampati-parvat",
    name: "Sampati Parvat",
    state: "Karnataka",
    country: "India",
    phase: "Search for Sita",
    latitude: 15.2833,
    longitude: 76.4167,
    description: "Mountain where Jatayu's brother Sampati provided crucial information about Sita's location",
    history: "Sampati was Jatayu's brother and a powerful eagle. When the Vanara army was searching for Sita, Sampati revealed her location in Lanka. Though old and weakened, Sampati's information was vital to the rescue mission.",
    spiritual: "Sampati Parvat represents the help that comes from unexpected sources when one is dedicated to a righteous cause. The visit grants blessings of receiving divine guidance and assistance in times of need.",
    cultural: "The mountain is celebrated in local traditions as a site of divine revelation. The story of Sampati teaches about the importance of imparting knowledge and helping others despite personal limitations.",
    events: "Temple celebrations, Pilgrimage activities, Spiritual retreats",
    temple: "Sampati Temple",
    bestTimeToVisit: "October to March",
    nearestCity: "Hospet",
    highlights: ["Mountain site", "Sacred temple", "Scenic views", "Meditation areas"]
  },
  {
    id: "mahendragiri-hill",
    name: "Mahendragiri Hill",
    state: "Odisha / Andhra Pradesh",
    country: "India",
    phase: "Return & Coronation",
    latitude: 18.8333,
    longitude: 84.0,
    description: "Sacred mountain where Hanuman made his legendary leap toward Lanka",
    history: "Mahendragiri Hill is traditionally believed to be the starting point of Hanuman's famous leap across the sea to Lanka. The mountain is sacred to both Hindu and Buddhist traditions with numerous temples and monasteries.",
    spiritual: "Mahendragiri is a place of extraordinary devotion and superhuman effort. Hanuman's leap symbolizes the transcendence of ordinary limitations through faith. Visiting grants blessings of strength, courage, and the ability to overcome seemingly impossible challenges.",
    cultural: "The mountain is a major pilgrimage center with ancient temples and monastic communities. Local traditions celebrate Hanuman's extraordinary devotion. The site is important for understanding the divine geography of the Ramayana.",
    events: "Hanuman Jayanti, Temple festivals, Mountain pilgrimages",
    temple: "Mahendragiri temples",
    bestTimeToVisit: "October to March",
    nearestCity: "Berhampur, Rayagada",
    highlights: ["Sacred summit", "Leap point", "Ancient temples", "Forest sanctuary", "Scenic vistas"]
  },
  {
    id: "trikuta-parvat",
    name: "Trikuta Parvat",
    state: "Western Province",
    country: "Sri Lanka",
    phase: "Return & Coronation",
    latitude: 6.7833,
    longitude: 80.8,
    description: "Three-peaked mountain in Lanka where Ravana's capital was situated",
    history: "Trikuta Parvat, the three-peaked mountain, was the location of Ravana's golden capital. The mountain overlooked the city and served as a defensive stronghold. Ravana's palace was built on this mountain with structures visible for miles.",
    spiritual: "Trikuta represents the heights of material power and the illusory nature of worldly dominion. Despite all his power, Ravana's pride led to his downfall. Visiting teaches lessons about humility and the transient nature of material power.",
    cultural: "The mountain is significant in Sri Lankan geography and history. Local culture celebrates the complex legacy of Ravana as both a powerful ruler and a flawed character. The site is important for understanding the Ramayana's cultural context.",
    events: "Historical tours, Guided pilgrimages, Educational programs",
    bestTimeToVisit: "October to February",
    nearestCity: "Colombo",
    highlights: ["Mountain peaks", "Palace site", "Archaeological remains", "Historical viewpoint"]
  },
  {
    id: "nikumbhila",
    name: "Nikumbhila",
    state: "Western Province",
    country: "Sri Lanka",
    phase: "Return & Coronation",
    latitude: 6.9,
    longitude: 80.8,
    description: "Sacred site where Indrajit performed yagna and created supernatural barriers",
    history: "Nikumbhila is where Indrajit, Ravana's powerful son, performed sacred rituals and yagna (sacrificial fire). The rituals created supernatural barriers that protected Lanka. When the barriers were broken, it led to Indrajit's eventual defeat.",
    spiritual: "Nikumbhila represents the consequences of misusing spiritual power for destructive purposes. The site teaches that true spiritual strength comes from righteous living, not from rituals performed with ill intent.",
    cultural: "The site is celebrated in Sri Lankan culture as a place of historical significance. Local traditions maintain the memory of these events through stories and ceremonies. The site is important for understanding the complex moral themes of the Ramayana.",
    events: "Historical tours, Cultural programs, Educational initiatives",
    bestTimeToVisit: "October to February",
    nearestCity: "Colombo",
    highlights: ["Ritual site", "Historical area", "Temple remains", "Sacred ground"]
  },
  {
    id: "kabandha-moksha",
    name: "Kabandha Moksha Sthal",
    state: "Karnataka",
    country: "India",
    phase: "Search for Sita",
    latitude: 15.2,
    longitude: 76.2,
    description: "Sacred place where Ram liberated the demon Kabandha granting him moksha",
    history: "Kabandha was a demon whose body was shaped like a trunk without a head or limbs. Though cursed to live as a demon, when Ram came, Kabandha asked for liberation and guidance. Ram blessed him and restored his original divine form.",
    spiritual: "Kabandha's story is about redemption and divine grace. No matter what form one takes or how far one has fallen, divine grace can restore and elevate the soul. The site grants blessings of redemption and second chances.",
    cultural: "The story teaches that physical appearance does not determine spiritual worth. Kabandha is celebrated as an example of seeking the divine and receiving grace. Local traditions celebrate the universality of divine compassion.",
    events: "Spiritual gatherings, Temple celebrations, Pilgrimage activities",
    temple: "Kabandha Liberation Temple",
    bestTimeToVisit: "October to March",
    nearestCity: "Hospet/Bellary",
    highlights: ["Temple site", "Sacred grounds", "Spiritual teaching area"]
  },
  {
    id: "bharata-milap",
    name: "Bharat Milap Site",
    state: "Madhya Pradesh",
    country: "India",
    phase: "Vanvās Begins",
    latitude: 25.2083,
    longitude: 80.8017,
    description: "Sacred spot at Chitrakoot where Ram met his brother Bharat during exile",
    history: "When Bharat learned of Ram's exile, he rushed to Chitrakoot to convince Ram to return and accept the throne. Though Bharat pleaded emotionally, Ram was bound by his father's vow and remained in exile. This meeting is celebrated as Bharat Milap.",
    spiritual: "Bharat Milap represents the ultimate sacrifice of personal desires for dharma and duty. Ram's unwavering commitment to his father's promise demonstrates divine virtue. The site grants blessings of righteousness and moral strength.",
    cultural: "The meeting of the two brothers is celebrated annually during Ram Navami with reenactments and celebrations. Bharat is revered for his devotion and sacrifice of personal ambition. The site is central to understanding Ram's character.",
    events: "Bharat Milap anniversary, Ramleela performances, Temple ceremonies",
    temple: "Bharat Milap Temple",
    bestTimeToVisit: "September to February",
    nearestCity: "Satna",
    highlights: ["Meeting site", "Ramghat", "Temple complex", "Pilgrimage area"]
  },
  {
    id: "nandigram",
    name: "Nandigram",
    state: "Uttar Pradesh",
    country: "India",
    phase: "Return & Coronation",
    latitude: 26.8617,
    longitude: 82.0442,
    description: "Place where Bharat waited with Ram's wooden sandals during the 14-year exile",
    history: "When Ram left for exile, Bharat refused to take the throne. Instead, he placed Ram's wooden sandals on the throne and ruled as a regent. At Nandigram, Bharat waited faithfully for Ram's return, maintaining the kingdom in perfect order.",
    spiritual: "Nandigram represents the ideal of service without ego and loyalty without reward. Bharat's devotion to his brother is considered the ultimate expression of sibling love and sacrifice. The site grants blessings of humility and righteous duty.",
    cultural: "Bharat is celebrated as the ideal younger brother in Hindu culture. His willingness to serve without seeking personal gain is a model for all relationships. Local traditions maintain ceremonies connected to Bharat's loyalty.",
    events: "Bharat Jayanti, Ram's return celebrations, Temple ceremonies",
    temple: "Bharat Temple",
    bestTimeToVisit: "October to March",
    nearestCity: "Faizabad",
    distance: "45 km from Ayodhya",
    highlights: ["Bharat Temple", "Throne with sandals site", "Pilgrimage area", "Historical site"]
  },
  {
    id: "ram-mandir",
    name: "Ram Mandir",
    state: "Uttar Pradesh",
    country: "India",
    phase: "Birth & Early Life / Return & Coronation",
    latitude: 26.8117,
    longitude: 82.0023,
    description: "The grand new Ram Mandir in Ayodhya, representing centuries of devotion and faith",
    history: "The newly constructed Ram Mandir is a magnificent structure built on the believed birthplace of Ram. The temple combines ancient Vedic architectural principles with modern construction techniques. It represents the fulfillment of centuries-old devotion and spiritual longing.",
    spiritual: "Ram Mandir is the ultimate destination for devotees seeking Ram's blessings. The energy at the temple is believed to be extraordinarily pure and elevating. Darshan (viewing) of the deity here grants divine grace, purification, and spiritual advancement.",
    cultural: "The construction and consecration of Ram Mandir is a defining event in contemporary Hindu culture. The temple represents national pride, spiritual aspiration, and devotional unity. Millions have been blessed by darshan and the temple's divine presence.",
    events: "Daily aarti, Ram Navami, Diwali, Special ceremonies, Darshan throughout the day",
    bestTimeToVisit: "October to March (for comfort); year-round for darshan",
    nearestCity: "Faizabad",
    highlights: ["Main sanctum", "Divine idol of Ram", "Architectural splendor", "Sacred Ghats", "Pilgrimage center"]
  },
  {
    id: "hanuman-dhara",
    name: "Hanuman Dhara",
    state: "Madhya Pradesh",
    country: "India",
    phase: "Vanvās Begins",
    latitude: 25.1733,
    longitude: 80.9008,
    description: "Waterfall where Hanuman performed tapasya and is believed to still meditate",
    history: "Hanuman Dhara is a sacred waterfall where Hanuman performed intense spiritual practice (tapasya) to deepen his devotion to Ram. The cool waters are believed to carry healing and spiritual properties. Hanuman is traditionally said to still meditate at this location.",
    spiritual: "The waterfall is a place of extraordinary spiritual power and devotional energy. Bathing in the waters and meditating here grants blessings of strength, courage, and unwavering devotion. The site is especially powerful for those seeking to deepen spiritual practice.",
    cultural: "Hanuman Dhara is an important pilgrimage center. The trek to reach the waterfall is considered a spiritual journey. Local communities maintain traditions of pilgrimage and spiritual practice at this sacred site.",
    events: "Hanuman Jayanti celebrations, Pilgrimage activities, Meditation gatherings",
    temple: "Hanuman Temple at the site",
    bestTimeToVisit: "September to February",
    nearestCity: "Satna",
    distance: "40 km from Chitrakoot",
    highlights: ["Sacred waterfall", "Meditation cave", "Temple complex", "Pilgrimage trail", "Natural beauty"]
  },
  {
    id: "guptar-ghat",
    name: "Guptar Ghat",
    state: "Uttar Pradesh",
    country: "India",
    phase: "Post-Coronation",
    latitude: 26.8292,
    longitude: 81.9917,
    description: "Sacred ghat on Sarayu River where Ram took his final departure in Jal Samadhi",
    history: "After ruling Ayodhya for thousands of years in the perfect Ram Rajya, Ram reached the end of his mortal life. At Guptar Ghat, he performed his final rituals and entered the Sarayu River in what's known as Jal Samadhi, transcending the mortal realm.",
    spiritual: "Guptar Ghat is the final pilgrimage site for Ram devotees. It represents the completion of the divine play (Leela) and the return to the eternal realm. Visiting grants blessings of wisdom about life's transience and the eternal nature of the soul.",
    cultural: "The ghat is revered as the most sacred spot for the final pilgrimage. Local traditions maintain elaborate ceremonies and rituals connected to Ram's departure. It's considered the ultimate destination for those completing their spiritual journey.",
    events: "Jal Samadhi anniversary celebrations, Final pilgrimage rituals, Spiritual gatherings",
    bestTimeToVisit: "October to March",
    nearestCity: "Ayodhya",
    highlights: ["Sacred ghat", "Departure site", "Spiritual power point", "Temple complex", "Pilgrimage center"]
  }
];

export const phases = [
  "Birth & Early Life",
  "Vanvās Begins",
  "Deep Forest Journey",
  "Search for Sita",
  "Return & Coronation",
  "Post-Coronation"
];
